// ============================================================================
// Booking Confirmation PDF Generator
// Generates a clean, professional booking confirmation using pdf-lib
// ============================================================================

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

interface BookingPdfData {
  passengerName: string;
  orgName: string;
  pnr: string;
  origin: string;
  originCity: string;
  destination: string;
  destinationCity: string;
  departureDate: string;
  departureTime: string;
  arrivalTime: string;
  airline: string;
  flightNumber: string;
  cabin: string;
  totalAmount: number;
  currency: string;
  bookingRef: string;
  status: string;
}

const IATA_TO_CITY: Record<string, string> = {
  DEL: "New Delhi", BOM: "Mumbai", BLR: "Bangalore", HYD: "Hyderabad",
  MAA: "Chennai", CCU: "Kolkata", PNQ: "Pune", AMD: "Ahmedabad",
  GOI: "Goa", JAI: "Jaipur", LKO: "Lucknow", COK: "Kochi",
  JFK: "New York", LHR: "London", DXB: "Dubai", SIN: "Singapore",
};

export function getCityName(code: string): string {
  return IATA_TO_CITY[code] ?? code;
}

export async function generateBookingConfirmationPdf(
  data: BookingPdfData
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4
  const { width, height } = page.getSize();

  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const fontRegular = await doc.embedFont(StandardFonts.Helvetica);

  const blue = rgb(0.0, 0.4, 0.8);
  const darkGray = rgb(0.2, 0.2, 0.2);
  const gray = rgb(0.5, 0.5, 0.5);
  const lightBg = rgb(0.96, 0.96, 0.98);

  let y = height - 50;
  const margin = 50;
  const contentWidth = width - margin * 2;

  // ── Header ──
  page.drawText("SkySwift", { x: margin, y, font: fontBold, size: 24, color: blue });
  page.drawText("Booking Confirmation", {
    x: margin, y: y - 25, font: fontRegular, size: 12, color: gray,
  });

  // PNR in top right
  page.drawText(`PNR: ${data.pnr}`, {
    x: width - margin - fontBold.widthOfTextAtSize(`PNR: ${data.pnr}`, 16),
    y, font: fontBold, size: 16, color: darkGray,
  });
  page.drawText(`Ref: ${data.bookingRef}`, {
    x: width - margin - fontRegular.widthOfTextAtSize(`Ref: ${data.bookingRef}`, 10),
    y: y - 18, font: fontRegular, size: 10, color: gray,
  });

  y -= 60;

  // ── Divider ──
  page.drawLine({
    start: { x: margin, y }, end: { x: width - margin, y },
    thickness: 1, color: rgb(0.9, 0.9, 0.9),
  });

  y -= 30;

  // ── Flight Details Box ──
  page.drawRectangle({
    x: margin, y: y - 120, width: contentWidth, height: 130,
    color: lightBg, borderWidth: 0,
  });

  // Route
  const routeText = `${data.originCity} (${data.origin})  →  ${data.destinationCity} (${data.destination})`;
  page.drawText(routeText, {
    x: margin + 20, y: y - 10, font: fontBold, size: 16, color: darkGray,
  });

  // Date and time
  page.drawText(data.departureDate, {
    x: margin + 20, y: y - 35, font: fontRegular, size: 12, color: darkGray,
  });
  if (data.departureTime && data.arrivalTime) {
    page.drawText(`${data.departureTime} – ${data.arrivalTime}`, {
      x: margin + 200, y: y - 35, font: fontRegular, size: 12, color: darkGray,
    });
  }

  // Airline and flight
  page.drawText(`${data.airline} ${data.flightNumber}`, {
    x: margin + 20, y: y - 60, font: fontBold, size: 12, color: darkGray,
  });
  page.drawText(`Cabin: ${data.cabin}`, {
    x: margin + 200, y: y - 60, font: fontRegular, size: 12, color: gray,
  });

  // Passenger
  page.drawText(`Passenger: ${data.passengerName}`, {
    x: margin + 20, y: y - 85, font: fontRegular, size: 12, color: darkGray,
  });
  page.drawText(`Company: ${data.orgName}`, {
    x: margin + 20, y: y - 105, font: fontRegular, size: 12, color: gray,
  });

  y -= 160;

  // ── Price ──
  const priceStr = data.currency === "INR"
    ? `₹${Math.round(data.totalAmount).toLocaleString("en-IN")}`
    : `${data.currency} ${data.totalAmount.toFixed(2)}`;

  page.drawText("Total Amount", {
    x: margin + 20, y, font: fontRegular, size: 12, color: gray,
  });
  page.drawText(priceStr, {
    x: margin + 20, y: y - 20, font: fontBold, size: 18, color: darkGray,
  });

  // Status badge
  const statusText = data.status.toUpperCase();
  page.drawText(statusText, {
    x: width - margin - fontBold.widthOfTextAtSize(statusText, 12) - 20,
    y: y - 10, font: fontBold, size: 12,
    color: data.status === "booked" ? rgb(0.0, 0.6, 0.3) : rgb(0.8, 0.5, 0.0),
  });

  y -= 60;

  // ── Divider ──
  page.drawLine({
    start: { x: margin, y }, end: { x: width - margin, y },
    thickness: 1, color: rgb(0.9, 0.9, 0.9),
  });

  y -= 30;

  // ── Footer ──
  page.drawText("This is an electronic booking confirmation generated by SkySwift.", {
    x: margin, y, font: fontRegular, size: 9, color: gray,
  });
  page.drawText("For support, contact your company's travel desk or reach us on WhatsApp.", {
    x: margin, y: y - 15, font: fontRegular, size: 9, color: gray,
  });

  return doc.save();
}
